### PR TITLE
Major CMake rework

### PR DESCRIPTION
**Pull request by Rinzii**
This PR is solely focused on making the CMake script more scalable. The issue I was running into before was it was super easy to miss files or not properly add them to the cmake. Now we are being significantly more explicit.

### CODE REVIEW

**Comment by Rinzii** [comment]
Also applied some minor bug fixes for Intel OneAPI DPC++Mostly just a quick fix to throw on top of this PR

**Comment by Rinzii** [comment]
Also ignore the failed check for the linter. I will fix all issues with the linter in a later PR.

**Review by nekoflare — COMMENTED** [review]
OK

**Review by nekoflare — COMMENTED** [review]
Also good

**Pull request merged**
