### PR TITLE
ldexp implementation

### PR DESCRIPTION
**Pull request by GDBobby**
equally as accurate as std::sin, 21-26x faster

### CODE REVIEW

**Review by Rinzii — CHANGES_REQUESTED** [review]
To continue with my review I require a suite of tests for ccm::ldexp that covers a set of data and edge cases for both double and float. Once those test cases have been made and passing I will continue with the review. 

Also thanks for the contribution! I am excited to read more of your approach and implementation. ^^

**Comment by Rinzii** [comment]
> equally as accurate as std::sin, 21-26x faster

Hey Bobby, what is the status of this PR currently?

**Comment by GDBobby** [comment]
Working on some other stuff at the moment, I'll wrap up the rest of the trig functions and add the unit test in a week or two

**Comment by GDBobby** [comment]
idk how to re-run the checks but i think i covered all the test cases

**Comment by Rinzii** [comment]
> idk how to re-run the checks but i think i covered all the test cases

Merged some changes I made on origin into your branch. Test will run now! ^^

**Comment by Rinzii** [comment]
Oh, I see why your failing to build. I made a change to the namespace of bits.hpp. It is no longer `ccm::helpers` but now `ccm::support`

**Comment by Rinzii** [comment]
Crap I accidentally merged the PR. Give me a moment to fix this.

**Pull request merged**
